name: carbon_design_system
description: IBM's open source design system for products and digital experiences.
version: 1.0.0
repository: https://github.com/fa-fifi/carbon_design_system

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # TODO: Remove icones dependency.
  icones: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:

flutter:
  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM Plex Mono/IBMPlexMono-BoldItalic.ttf
          weight: 700
          style: italic

    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM Plex Sans/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic

    - family: IBM Plex Serif
      fonts:
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM Plex Serif/IBMPlexSerif-BoldItalic.ttf
          weight: 700
          style: italic