name: progrid
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  carbon_design_system:
    path: packages/carbon_design_system
  cloud_firestore: ^5.5.0
  device_info_plus: ^11.1.1
  excel: ^4.0.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  image_watermark: ^0.1.0
  intl: ^0.20.1
  latlong2: ^0.9.1
  # maps_launcher: ^2.2.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/